import Head from 'next/head'
import Header from '../components/commen/Header'
import Navbar from '../components/commen/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
<Header/>
      {/* navbar */}
<Navbar/>
      {/* result */}
    
    </div>
  )
}
